#+TITLE: KeePass CLI with Emacs Integration
#+AUTHOR: yufu

* Why KeePass
- I don't want to pay for password managers anymore. Especially most of them are subscription-based.
- GNU Pass is good, but it's hard to interact with it outside of terminal.

* Why New CLI
- UI/UX of =keepassxc-cli= is not friendly.
  - =keepassxc-cli= can only list the title of entry. However, only showing the title might not be enough in some cases. Even worse, there might be entries with the exact same title.
- Need to parse CLI output to get the information we want.
- Above reasons make it really difficult to develop a good Emacs package to retrieve passwords.


* Feature
- List the entries with user-specified fields =keepass-cli -d <DATABSE> ls -f title username=
- Server mode =keepass-cli -d <DATABASE> server --emacs=

* Goal


* Installation
** CLI binary
#+begin_src shell
  cargo install --path .
#+end_src
** Emacs integration
#+begin_src emacs-lisp
  (add-to-list 'load-path "/Users/fuyu0425/project/github/keepass-cli-rs/")
  (require 'keepass)
  (setq keepass-database "/Users/fuyu0425/keepass/keepass.kdbx")
  (keepass-make-hydra-favorite
   ("t" "test")
   ("o" "totp seed"))
  ;; for spacemacs with SPC a k
  (spacemacs/set-leader-keys
    "ak" 'keepass-inplace)
#+end_src
There are two functions: =keepass= and =keepass-inplace=.
=keepass= will switch to a special buffer =keepass:main=.
=keepass-inplace= will not.


* Contribution
I have listed some TODOs in =TODOs.org=.
Welcome PR and discussion.

* Credit
- [[https://github.com/djcb/mu][mu/mu4e code base]]
  - idiom way to interact with asynchronous processes.
- [[https://github.com/ifosch/keepass-mode][keepass-mode]]
- [[https://gitlab.com/tay-dev/keepass.el][keepass.el]]
